config/routes.rb
Rails.application.routes.draw do
  devise_for :donators, path: 'donators', controllers: { sessions: "donators/sessions", registrations: 'donators/registrations' }
  devise_for :teachers, path: 'teachers', controllers: { sessions: "teachers/sessions", registrations: 'teachers/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :donations, only: [:new, :create, :index, :update, :edit]
    resources :project_photos, only: [:create]
    resources :donators, only: [:index]
  end
  resources :payments, only: [:new]
  resources :project_photos, only: [:destroy]
  root to: 'pages#home'
  get 'institucional', to: 'pages#institucional', as: :institucional
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :project
  belongs_to :donator
  validates :quantity_donated, presence: true
  validates :status, presence: true

  after_update :check_status

  def check_status
    if self.status == "doação recebida"
      project = self.project
      project.total_donations += self.quantity_donated
      project.save
    end
  end

end

app/models/donator.rb
class Donator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :donations
  has_many :payments
  validates :name, presence: true
  validates :last_name, presence: true
  validates :cpf, presence: true
  validates :telephone, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  # belongs_to :donator
  # validates :status, presence: true
  # validates :date, presence: true
  # validates :value_cents, presence: true
  # validates :duration, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :teacher
  has_many :project_photos, dependent: :destroy
  has_many :donations
  has_many :donators, through: :donations
  validates :title, presence: true
  validates :description, presence: true
  validates :material, presence: true
  validates :quantity, presence: true
  validates :average_unit_price, presence: true
  validates :category, presence: true
  validates :limit_date, presence: true

  accepts_nested_attributes_for :project_photos

  after_update :complete_project

  def complete_project
    self.status = "Finalizado" if self.total_donations >= self.quantity
    self.save if self.status_changed?
  end

end

app/models/project_photo.rb
class ProjectPhoto < ApplicationRecord
  belongs_to :project
  mount_uploader :photo, PhotoUploader
end

app/models/school.rb
class School < ApplicationRecord
  # has_many :teachers
  # has_many :projects, through: :teacher
  validates :address, presence: true
  validates :name, presence: true
  validates :city, presence: true
  validates :state, presence: true
end

# require 'nokogiri'
# require 'open-uri'
# require 'byebug'

# def scraper
#   url = 'http://www.educacao.sp.gov.br/central-de-atendimento/consulta.asp?'
#   unparsed_page = open(url).read
#   parsed_page = Nokogiri::HTML(unparsed_page)
#   byebug
# end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # belongs_to :school
  has_many :projects, dependent: :destroy
  has_many :donation, through: :projetos
  validates :name, presence: true
  validates :last_name, presence: true
  validates :registration_code, presence: true
  validates :course, presence: true
  validates :telephone, presence: true
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_donator!, only: [:create, :new]
  before_action :authenticate_teacher!, only: [:edit, :update]


  def index
    # @donations = Donation.all
    @donations = policy_scope(Donation)
  end

  def show
    @donation = Donation.find(params[:id])
    authorize @donation
  end

  def new
    @project = Project.find(params[:project_id])
    @donation = Donation.new
    authorize @donation
  end

  def create
    @project = Project.find(params[:project_id])
    @donation = Donation.new(donation_params)
    @donation.project = @project
    @user = current_donator
    @donation.donator = @user
    authorize @donation
    if @donation.save
      redirect_to project_path(@project)
    # raise
    else render :new
    end
  end

  def update
    @donation = Donation.find(params[:id])
    authorize @donation
    if @donation.update(donation_params)
      redirect_to project_path(@donation.project), notice: 'A doação foi atualizada'
    else
      render :edit
    end
    # raise
  end

  def edit
    # raise
    @donation = Donation.find(params[:id])
    @project = Project.find(params[:project_id])
    @donation.project = @project
    @project.teacher = current_teacher
    authorize @donation
  end

  private

  def donation_params
    params.require(:donation).permit(:status, :quantity_donated)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def institucional
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
  end

  def create
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_teacher!, only: [:create, :new, :update, :edit]
  def index
    # @projects = Project.all
    @projects = policy_scope(Project)
    # raise

    if params[:keyword].present?
      @projects = @projects.where("title ILIKE?", "%#{params[:keyword]}%")
    end

    if params[:category].present?
      @projects = @projects.where(category: params[:category])
    end

    # raise
  end

  def show
    authorize @project
    # raise
  end

  def new
    @project = Project.new
    authorize @project
    # raise
  end

  def create
    @project = Project.new(project_params)
    @project.teacher = current_teacher
    # raise
    authorize @project
      if params[:project_photos].nil?
      else
      save_photos
      end
      # raise
    @project.teacher.id = current_teacher.id
    # raise
    if @project.save
      # raise
      redirect_to project_path(@project), notice: 'Seu projeto foi criado'
    else
      render 'projects/show'
    end
    # # raise
  end

  def update
    # raise
    # @project.teacher = @teacher
    authorize @project
      if params[:project_photos].nil?
      else
      save_photos
      end
    if @project.update(project_params)
      redirect_to project_path(@project), notice: 'Seu projeto foi atualizado'
    else
      render :edit
    end
  end

  def edit
    # @project.teacher = @teacher
    authorize @project
  end


  def destroy
    authorize @project
    @project.destroy
    redirect_to projects_path, notice: 'Seu projeto foi deletado com sucesso'
  end
  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :material, :quantity, :average_unit_price, :category, :limit_date, project_photos: [])
  end

  def save_photos
    # raise
      params[:project_photos].each do |photo|
      project_photo = ProjectPhoto.new
      project_photo.photo = photo
      @project.project_photos << project_photo
      project_photo.save
    end
  end
end

app/controllers/schools_controller.rb
# class SchoolsController < ApplicationController
#   # GET /schools
#   # GET /schools.json
#   def index
#   url = 'http://www.educacao.sp.gov.br/central-de-atendimento/consulta.asp?'
#   unparsed_page = open(url).read
#   parsed_page = Nokogiri::HTML(unparsed_page)

#   end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Educandomais</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <script type="text/javascript" defer src="https://donorbox.org/install-popup-button.js"></script>
    <script>window.DonorBox = { widgetLinkClassName: 'custom-dbox-popup' }</script>
<!--     <script src="js/jquery-1.7.1.min.js"></script>
    <script src="js/bootstrap.js"></script>
 -->
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>

<div class="banner" style="background-image: url(<%=asset_path('blackboard.jpg')%>);">
  <div class="container">
    <h1>Garantir a qualidade do ensino público é um dever de todos</h1>
    <p>Envolva-se com as necessidades de escolas públicas ao seu redor</p>
    <div class="banner-btn">
    <a class="btn btn-flat mr-4" href="/projects/new">Sou Professor</a>
    <a class="btn btn-flat ml-4" href="#">Quero Ajudar</a>
    </div>
  </div>
</div>

<div class="como-funciona-container">
  <div class="como-funciona-texto">
    <h1>Como Atuamos</h1>
    <p>.......</p>
    <div class="como-funciona-btn">
      <a class="btn btn-flat mr-4" href="/projects/new">Sou Professor, quero criar projeto</a>
      <a class="btn btn-flat ml-4" href="#">Quero encontrar projetos para ajudar</a>
    </div>
  </div>
  <div class="como-funciona-foto">

  </div>
</div>

<%= render 'shared/footer' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    footer info
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Educatio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/projects">Projetos</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="/institucional" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Institucional
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/institucional">Quem Somos</a>
          <a class="dropdown-item" href="/institucional">Apoiadores</a>
          <a class="dropdown-item" href="/institucional">Relatório de atividades</a>
        </div>
      </li>
      <li class="nav-item">
        <% if !(teacher_signed_in? || donator_signed_in?) %>
        <a class="nav-link" href="/teachers/sign_in">Sou professor</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/donators/sign_in">Quero doar</a>
        <% elsif teacher_signed_in? %>
        <%= link_to "Log out", destroy_teacher_session_path, method: :delete, class: 'nav-link' %>
        <% else %>
        <%= link_to "Log out", destroy_donator_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>