config/routes.rb
Rails.application.routes.draw do
  devise_for :donators, path: 'donators', controllers: { sessions: "donators/sessions", registrations: 'donators/registrations' }
  devise_for :teachers, path: 'teachers', controllers: { sessions: "teachers/sessions", registrations: 'teachers/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :donations, only: [:new, :create, :index, :update, :edit]
    resources :project_photos, only: [:create]
    resources :donators, only: [:index]
  end
  resources :payments, only: [:new]
  resources :project_photos, only: [:destroy]
  root to: 'pages#home'
  get 'institucional', to: 'pages#institucional', as: :institucional
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :teacher
  has_many :project_photos, dependent: :destroy
  has_many :donations
  has_many :donators, through: :donations
  validates :title, presence: true
  validates :description, presence: true
  validates :material, presence: true
  validates :quantity, presence: true
  validates :average_unit_price, presence: true
  validates :category, presence: true
  validates :limit_date, presence: true

  accepts_nested_attributes_for :project_photos

  after_update :complete_project

  def complete_project
    self.status = "Finalizado" if self.total_donations >= self.quantity
    self.save if self.status_changed?
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_teacher!, only: [:create, :new, :update, :edit]
  def index
    # @projects = Project.all
    @projects = policy_scope(Project)
    # raise

    if params[:keyword].present?
      @projects = @projects.where("title ILIKE?", "%#{params[:keyword]}%")
    end

    if params[:category].present?
      @projects = @projects.where(category: params[:category])
    end

    # raise
  end

  def show
    authorize @project
    # raise
  end

  def new
    @project = Project.new
    authorize @project
    # raise
  end

  def create
    @project = Project.new(project_params)
    @project.teacher = current_teacher
    # raise
    authorize @project
      if params[:project_photos].nil?
      else
      save_photos
      end
      # raise
    @project.teacher.id = current_teacher.id
    # raise
    if @project.save
      # raise
      redirect_to project_path(@project), notice: 'Seu projeto foi criado'
    else
      render 'projects/show'
    end
    # # raise
  end

  def update
    # raise
    # @project.teacher = @teacher
    authorize @project
      if params[:project_photos].nil?
      else
      save_photos
      end
    if @project.update(project_params)
      redirect_to project_path(@project), notice: 'Seu projeto foi atualizado'
    else
      render :edit
    end
  end

  def edit
    # @project.teacher = @teacher
    authorize @project
  end


  def destroy
    authorize @project
    @project.destroy
    redirect_to projects_path, notice: 'Seu projeto foi deletado com sucesso'
  end
  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :material, :quantity, :average_unit_price, :category, :limit_date, project_photos: [])
  end

  def save_photos
    # raise
      params[:project_photos].each do |photo|
      project_photo = ProjectPhoto.new
      project_photo.photo = photo
      @project.project_photos << project_photo
      project_photo.save
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_carousel.html.erb
 <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @project.project_photos.each_with_index do |p, index| %>
    <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= 'active' if p == @project.project_photos[0] %>"></li>
    <% end %>
  </ol>
  <div class="carousel-inner" style="width: 500px">
    <% @project.project_photos.each do |pre| %>
    <div class="carousel-item <%= 'active' if pre == @project.project_photos[0] %>">
      <%= cl_image_tag pre.photo, width: 500, height: 400, crop: :fill %>
    </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/projects/_filterform.html.erb
<div class="filter-form">
<%= form_tag projects_path, method: :get do %>
  <div class="keyword-filter" id="filter-input">
    <%= text_field_tag :keyword,
      params[:keyword],
      class: "form-control",
      placeholder: "Palavra-chave"%>
  </div>

  <div class="category-filter" id="filter-input">
    <%= text_field_tag :category,
      params[:category],
      class: "form-control",
      placeholder: "Categoria do projeto"

    %>
  </div>

<!--   <div class="category-filter" id="filter-input">
    <%=# text_field_tag :urgency,
      # params[:urgency],
      # class: "form-control",
      # placeholder: "Nível de urgência"

    %>
  </div> -->

  <div class="filter-btn" id="filter-input">
    <%= submit_tag "Buscar", class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/projects/_photoform.html.erb
_photoform.html.erb

app/views/projects/edit.html.erb
<div class="project-form">
  <h1>Edite seu projeto</h1>
  <%= simple_form_for @project, html: { class: 'project-form' } do |f| %>
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.input :category %>
    <%= f.input :material %>
    <%= f.input :quantity%>
    <%= f.input :average_unit_price %>
    <%= f.input :school_year%>
    <%= f.input :limit_date %>
    <%= f.simple_fields_for :photo, ProjectPhoto.new do |photo_form| %>
      <%= photo_form.file_field :photo, multiple: true, name: "project_photos[]" %>
    <% end %>
    <% @project.project_photos.each do |photo|%>
      <p><%= cl_image_tag photo.photo, width: 500, height: 400, crop: :fill %></p>
        <%= link_to "delete", project_photo_path(photo), method: :delete %>
    <% end %>
    <%= f.button :submit, class: 'btn btn-outline-success' %>
  <% end %>
  <%= link_to "Voltar ao projeto", project_path(@project), class: 'btn', id:'back-to-project' %>
</div>

app/views/projects/index.html.erb
<%= render 'shared/navbar' %>

<div class="project-container">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.8)), url(<%=asset_path('chalk.jpg')%>)">
  PROJETOS ESCOLARES
  </div>

  <div class="project-top">
    <div class="project-title">
      <h1>Encontre projetos para apoiar</h1>
    </div>
    <div class="project-new-btn">
      <a class="btn btn-flat" href="/projects/new"><i class=" mr-2 fas fa-plus"></i>Criar novo projeto</a>
    </div>
  </div>
  <div class="project-filters">
  <%= render 'filterform' %>
  </div>
  <div class="project-index">
      <div class="project-cards">
        <% @projects.each do |project| %>
          <div class="project-card">
        <%= link_to project_path(project) do  %>
            <% if project.project_photos[0].nil? %>
               no photo
            <% else %>
              <div class="project-img">
                <%= cl_image_tag project.project_photos[0].photo%>
              </div>
            <% end %>
            <div class="card-title">
            <h4><%= link_to project.title, project_path(project) %></h4>
               <%= link_to project_path(project) do  %>
            <p class="card-subtitle mb-2 text-muted"><%= project.description[0..30] %>...[veja mais]</p>
            </div>
            <% end %>
             <%= link_to project_path(project) do  %>
            <div class="project-items">
            <p><i class="fas fa-pencil-ruler"></i>  <%= project.category %></p>
            <p><i class="fas fa-hand-holding-heart"></i>  <%= project.material %></p>
            <p><i class="fas fa-calculator"></i>  <%= project.quantity %> unidades </p>
            <p><i class="far fa-calendar-alt"></i>   <%= project.limit_date.strftime("%d/%m/%Y") %></p>
            </div>
            <% end %>
            <% end %>

          </div>
          <% end %>
      </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/projects/new.html.erb
<div class="project-form">
  <h1>Crie uma solicitação para seu projeto</h1>
  <p>Sua sala de aula, ou a escola para qual trabalha, precisa de doação de algum material? Seja ele material escolar, material para obras de expansão, renovação e construção de espaços ou itens básicos para o funcionamento do dia a dia de uma escola?</p>
  <%= simple_form_for @project, html: { class: 'project-form' } do |f| %>
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.input :category %>
    <%= f.input :material %>
    <%= f.input :quantity%>
    <%= f.input :average_unit_price %>
    <%= f.input :school_year%>
    <%= f.input :limit_date %>

    <%= f.simple_fields_for :project_photo, ProjectPhoto.new do |photo_form| %>
    <%= photo_form.file_field :project_photo, multiple: true, name: "project_photos[]" %>
    <% end %>
    <%= f.button :submit, class: 'btn btn-outline-success' %>
  <% end %>
  <%= link_to "Exibir projetos", projects_path, class: 'btn', id:'back-to-project' %>
</div>

app/views/projects/show.html.erb
<%= render 'shared/navbar' %>

<div class="project-show-title">
  <h1><%= @project.title %></h1>
  <div class="project-show-description">
  <h5><%= @project.description %></h5>
  </div>
</div>
<div class='project-show-container'>

  <div class='project-show-details'>
    <div class='project-show-details-one'>
      <h3>Detalhes do projeto</h3>
        <p>Material solicitado:<%= @project.material %></p>
        <p>Quantidade solicitada:<%= @project.quantity %></p>
        <p>Preço médio:<%= @project.average_unit_price %></p>
        <p>Categoria:<%= @project.category %></p>
        <p>Ano letivo:<%= @project.school_year %></p>
        <p>Data limite para doação:<%= @project.limit_date %></p>
      </div>
      <div class='project-show-details-two'>
        <% if (@project.teacher == current_teacher) %>
          <% if policy(@project).edit? %>
            <%= link_to "Editar projeto", edit_project_path(@project), class: "btn btn-flat"  %>
          <% end %>
        <% end %>
        <% if !(@project.teacher == current_teacher) %>
          <%= link_to "Doe material", new_project_donation_path(@project), class: "btn btn-flat" %>
        <% end %>
      </div>
  </div>
  <div class='project-show-photos'>
    <%= render 'carousel' %>
  </div>
  <div class='project-show-teacher-donation'>
    <div class='project-show-teacher'>
      <h3>Perfil do professor</h3>
        <p><%= @project.teacher.name %></p>
        <p><%= @project.teacher.last_name %></p>
        <p><%#= @project.teacher.school.name %></p>
    </div>
    <div class='project-show-donation'>
        <% if (@project.teacher == current_teacher)%>
          <h3>Doações recebidas</h3>
          <% @project.donations.each do |donation| %>
            <p><%= donation.donator.name %></p>
            <p><%= donation.status %></p>
            <p><%= donation.quantity_donated %></p>
            <p><%= link_to "Editar status da doação", edit_project_donation_path(donation.project, donation), class: "btn btn-flat" %></p>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>